replicaCount: 1

image:
  repository: daiberiafleetopsacr.azurecr.io/fleet-api
  pullPolicy: Always
  tag: 04258a6040120af2fce64913f2be2726aeaa9ab3

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  host: fleet-api.51.103.15.240.nip.io
  tls: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

keyvault:
  vaultName: daiberia-fleetops-kv
  tenantId: "8799ccb4-1532-4247-a0a1-7b2e74062950"
  clientId: "8c3bed2d-26ae-470c-b3c8-2d09816a1eb2"

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8000"
  prometheus.io/path: "/metrics"

# M1: CORS — orígenes permitidos explícitos, sin wildcard
cors:
  allowedOrigins: "https://daiberia.xyz,https://fleet-api.51.103.15.240.nip.io"