replicaCount: 1

image:
  repository: daiberiafleetopsacr.azurecr.io/fleet-api
  pullPolicy: Always
  tag: 672cb0fb6deb093ea5dc9e8d2834692f1988f3b0

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  host: fleet-api.51.103.15.240.nip.io
  tls: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

keyvault:
  vaultName: daiberia-fleetops-kv
  tenantId: ***TENANT_ID***
  clientId: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8000"
  prometheus.io/path: "/metrics"