# cluster/grafana-secrets.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  provider: azure
  parameters:
    keyvaultName: daiberia-fleetops-kv
    objects: |
      array:
        - |
          objectName: fleetops-grafana-user
          objectType: secret
          objectVersion: ""
        - |
          objectName: fleetops-grafana-password
          objectType: secret
          objectVersion: ""
    tenantId: "8799ccb4-1532-4247-a0a1-7b2e74062950"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "8c3bed2d-26ae-470c-b3c8-2d09816a1eb2"
  secretObjects:
  - secretName: grafana-admin-secret
    type: Opaque
    data:
    - objectName: fleetops-grafana-user
      key: admin-user
    - objectName: fleetops-grafana-password
      key: admin-password
